name: Dry Run Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  dry-run-check:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install psutil
    
    - name: Run dry_run.bat
      run: |
        cmd /c dry_run.bat
      shell: cmd
    
    - name: Check for errors
      run: |
        if %ERRORLEVEL% neq 0 (
          echo "Error occurred during dry run"
          exit 1
        ) else (
          echo "Dry run completed successfully"
        )
      shell: cmd
