name: Python Linting

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: windows-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
    
    - name: Run flake8
      id: lint
      run: |
        # Run flake8 on specific Python files and save the output to a file
        flake8 logger2.py convert.py mail.py > flake8.log
        if ($LASTEXITCODE -ne 0) {
          Write-Host "flake8 reported issues."
          exit $LASTEXITCODE
        }
      shell: pwsh
    
    - name: Check for errors
      run: |
        # Check the flake8.log for errors
        $logContent = Get-Content flake8.log
        if ($logContent) {
          Write-Host "Linting errors found in the following files:"
          $logContent | ForEach-Object {
            Write-Host $_
          }
          exit 1
        } else {
          Write-Host "No linting errors found."
        }
      shell: pwsh
